### ISSUE TITLE
KeyError: 'ciphersuites'

### ISSUE THREAD

**Issue by dsolstad** [mozilla/cipherscan#182] opened 2019-07-17 17:52 UTC
Hi. I just cloned the current release and after trying analyze.py I get this:
```
root@kali:~/cipherscan# python analyze.py -t domain:443
Traceback (most recent call last):
  File "analyze.py", line 491, in <module>
    main()
  File "analyze.py", line 476, in main
    exit_status=process_results(str(data), args.level, args.json, args.nagios)
  File "analyze.py", line 364, in process_results
    measured_lvl = evaluate_all(results)
  File "analyze.py", line 312, in evaluate_all
    if is_old(results):
  File "analyze.py", line 124, in is_old
    if conn['cipher'] not in old["ciphersuites"]:
KeyError: 'ciphersuites'
```

**Comment by autopwn** [comment] 2019-07-18 12:41
Hi @dsolstad,

this issue is already handled in https://github.com/mozilla/cipherscan/issues/180 but is still due to be merged.

**Comment by tomato42** [comment] 2019-07-26 16:28
duplicate of #180

**Closed by tomato42** 2019-07-26 16:28 UTC
